"""empty message

Revision ID: 5a96c9b16b55
Revises: 71ff6bbeca04
Create Date: 2026-06-26 00:18:13.156070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a96c9b16b55'
down_revision = '71ff6bbeca04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meteorological',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freak', sa.String(length=120), nullable=False),
    sa.Column('cat', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freak_id', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(length=700), nullable=False),
    sa.ForeignKeyConstraint(['freak_id'], ['meteorological.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation')
    op.drop_table('users')
    op.drop_table('meteorological')
    # ### end Alembic commands ###
