"""empty message

Revision ID: 61336029ed77
Revises: 5a96c9b16b55
Create Date: 2026-06-26 10:35:30.666610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61336029ed77'
down_revision = '5a96c9b16b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
